<?php



/**
 * Skeleton subclass for representing a row from the 'movie_propel_i18n' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.1 on:
 *
 * 09/09/11 18:01:24
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class MoviePropelI18n extends BaseMoviePropelI18n {
    /**
     * @param array $fields
     * @return MoviePropelI18n
     */
    public static function create(array $fields)
    {
        $i18n = new MoviePropelI18n();
        $i18n->fromArray($fields, BasePeer::TYPE_FIELDNAME);
        $i18n->save();

        return $i18n;
    }
} // MoviePropelI18n
